// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: stroeer/page/section/v1/section_page_service.proto

//*
// @FileArticle ⚙︎ SectionPageService

package section

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSectionPageResponse_PaginationType int32

const (
	// Not specified.
	GetSectionPageResponse_PAGINATION_TYPE_UNSPECIFIED GetSectionPageResponse_PaginationType = 0
	// The default pagination type.
	GetSectionPageResponse_FIXED_BLOCK GetSectionPageResponse_PaginationType = 1
	// Pagination type for Evergreen-Ressorts.
	GetSectionPageResponse_GHOST_BLOCK GetSectionPageResponse_PaginationType = 2
)

// Enum value maps for GetSectionPageResponse_PaginationType.
var (
	GetSectionPageResponse_PaginationType_name = map[int32]string{
		0: "PAGINATION_TYPE_UNSPECIFIED",
		1: "FIXED_BLOCK",
		2: "GHOST_BLOCK",
	}
	GetSectionPageResponse_PaginationType_value = map[string]int32{
		"PAGINATION_TYPE_UNSPECIFIED": 0,
		"FIXED_BLOCK":                 1,
		"GHOST_BLOCK":                 2,
	}
)

func (x GetSectionPageResponse_PaginationType) Enum() *GetSectionPageResponse_PaginationType {
	p := new(GetSectionPageResponse_PaginationType)
	*p = x
	return p
}

func (x GetSectionPageResponse_PaginationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetSectionPageResponse_PaginationType) Descriptor() protoreflect.EnumDescriptor {
	return file_stroeer_page_section_v1_section_page_service_proto_enumTypes[0].Descriptor()
}

func (GetSectionPageResponse_PaginationType) Type() protoreflect.EnumType {
	return &file_stroeer_page_section_v1_section_page_service_proto_enumTypes[0]
}

func (x GetSectionPageResponse_PaginationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetSectionPageResponse_PaginationType.Descriptor instead.
func (GetSectionPageResponse_PaginationType) EnumDescriptor() ([]byte, []int) {
	return file_stroeer_page_section_v1_section_page_service_proto_rawDescGZIP(), []int{1, 0}
}

// *
// Message to provide parameters when requesting data for a section page, currently only the path of the page.
// Correct paths have a leading and a trailing slash, like `/nachrichten/unterhaltung/`
// The homepage has the path `/`.
//
// ```protobuf
//
//	message GetSectionPageRequest {
//	  // valid section_path, with leading and trailing slash
//	  string section_path = 1;
//
//	  // use to page through sections. If unspecified, it will default to `1`.
//	  // Paging is 1-based (1 is the first page, there is no page `0`)
//	  //
//	  // Due to underlying mechanisms and seo requirements, page-size is fixed at 30
//	  // The service may return fewer than this value.
//	  int32 page = 2;
//	}
//
// ```
type GetSectionPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// valid section_path, with leading and trailing slash
	SectionPath string `protobuf:"bytes,1,opt,name=section_path,json=sectionPath,proto3" json:"section_path,omitempty"`
	// use to page through sections. If unspecified, it will default to `1`.
	// Paging is 1-based (1 is the first page, there is no page `0`)
	//
	// Due to underlying mechanisms and seo requirements, page-size is fixed at 30
	// The service may return fewer than this value.
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetSectionPageRequest) Reset() {
	*x = GetSectionPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_page_section_v1_section_page_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSectionPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectionPageRequest) ProtoMessage() {}

func (x *GetSectionPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_page_section_v1_section_page_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectionPageRequest.ProtoReflect.Descriptor instead.
func (*GetSectionPageRequest) Descriptor() ([]byte, []int) {
	return file_stroeer_page_section_v1_section_page_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetSectionPageRequest) GetSectionPath() string {
	if x != nil {
		return x.SectionPath
	}
	return ""
}

func (x *GetSectionPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// *
// Response message when requesting data for a section page.
// Responds with `NOT_FOUND` if an unknown path is requested, or the path is incorrect.
//
// ```protobuf
// message GetSectionPageResponse {
// stroeer.page.section.v1.SectionPage section_page = 1;
//
//	// Total number of pages in this `section_path`
//
// int32 total_pages = 2;
//
// PaginationType pagination_type = 3;
//
//	 enum PaginationType {
//	   // Not specified.
//	   PAGINATION_TYPE_UNSPECIFIED = 0;
//
//	   // The default pagination type.
//	   FIXED_BLOCK = 1;
//
//	   // Pagination type for Evergreen-Ressorts.
//	   GHOST_BLOCK = 2;
//	 }
//	}
//
// ```
type GetSectionPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SectionPage *SectionPage `protobuf:"bytes,1,opt,name=section_page,json=sectionPage,proto3" json:"section_page,omitempty"`
	// Total number of pages in this `section_path`
	TotalPages     int32                                 `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	PaginationType GetSectionPageResponse_PaginationType `protobuf:"varint,3,opt,name=pagination_type,json=paginationType,proto3,enum=stroeer.page.section.v1.GetSectionPageResponse_PaginationType" json:"pagination_type,omitempty"`
}

func (x *GetSectionPageResponse) Reset() {
	*x = GetSectionPageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_page_section_v1_section_page_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSectionPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectionPageResponse) ProtoMessage() {}

func (x *GetSectionPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_page_section_v1_section_page_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectionPageResponse.ProtoReflect.Descriptor instead.
func (*GetSectionPageResponse) Descriptor() ([]byte, []int) {
	return file_stroeer_page_section_v1_section_page_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSectionPageResponse) GetSectionPage() *SectionPage {
	if x != nil {
		return x.SectionPage
	}
	return nil
}

func (x *GetSectionPageResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetSectionPageResponse) GetPaginationType() GetSectionPageResponse_PaginationType {
	if x != nil {
		return x.PaginationType
	}
	return GetSectionPageResponse_PAGINATION_TYPE_UNSPECIFIED
}

var File_stroeer_page_section_v1_section_page_service_proto protoreflect.FileDescriptor

var file_stroeer_page_section_v1_section_page_service_proto_rawDesc = []byte{
	0x0a, 0x32, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x73,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x61,
	0x67, 0x65, 0x2e, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x2a, 0x73,
	0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0xc0, 0x02, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x74, 0x72,
	0x6f, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x67, 0x65,
	0x52, 0x0b, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x67,
	0x0a, 0x0f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3e, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65,
	0x72, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x53, 0x0a, 0x0e, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x50, 0x41, 0x47,
	0x49, 0x4e, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x49,
	0x58, 0x45, 0x44, 0x5f, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x47,
	0x48, 0x4f, 0x53, 0x54, 0x5f, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x02, 0x32, 0x89, 0x01, 0x0a,
	0x12, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e,
	0x70, 0x61, 0x67, 0x65, 0x2e, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e,
	0x70, 0x61, 0x67, 0x65, 0x2e, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x53, 0x0a, 0x1a, 0x64, 0x65, 0x2e, 0x73,
	0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d,
	0x74, 0x61, 0x70, 0x69, 0x72, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stroeer_page_section_v1_section_page_service_proto_rawDescOnce sync.Once
	file_stroeer_page_section_v1_section_page_service_proto_rawDescData = file_stroeer_page_section_v1_section_page_service_proto_rawDesc
)

func file_stroeer_page_section_v1_section_page_service_proto_rawDescGZIP() []byte {
	file_stroeer_page_section_v1_section_page_service_proto_rawDescOnce.Do(func() {
		file_stroeer_page_section_v1_section_page_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_stroeer_page_section_v1_section_page_service_proto_rawDescData)
	})
	return file_stroeer_page_section_v1_section_page_service_proto_rawDescData
}

var file_stroeer_page_section_v1_section_page_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stroeer_page_section_v1_section_page_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stroeer_page_section_v1_section_page_service_proto_goTypes = []interface{}{
	(GetSectionPageResponse_PaginationType)(0), // 0: stroeer.page.section.v1.GetSectionPageResponse.PaginationType
	(*GetSectionPageRequest)(nil),              // 1: stroeer.page.section.v1.GetSectionPageRequest
	(*GetSectionPageResponse)(nil),             // 2: stroeer.page.section.v1.GetSectionPageResponse
	(*SectionPage)(nil),                        // 3: stroeer.page.section.v1.SectionPage
}
var file_stroeer_page_section_v1_section_page_service_proto_depIdxs = []int32{
	3, // 0: stroeer.page.section.v1.GetSectionPageResponse.section_page:type_name -> stroeer.page.section.v1.SectionPage
	0, // 1: stroeer.page.section.v1.GetSectionPageResponse.pagination_type:type_name -> stroeer.page.section.v1.GetSectionPageResponse.PaginationType
	1, // 2: stroeer.page.section.v1.SectionPageService.GetSectionPage:input_type -> stroeer.page.section.v1.GetSectionPageRequest
	2, // 3: stroeer.page.section.v1.SectionPageService.GetSectionPage:output_type -> stroeer.page.section.v1.GetSectionPageResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stroeer_page_section_v1_section_page_service_proto_init() }
func file_stroeer_page_section_v1_section_page_service_proto_init() {
	if File_stroeer_page_section_v1_section_page_service_proto != nil {
		return
	}
	file_stroeer_page_section_v1_section_page_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_stroeer_page_section_v1_section_page_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSectionPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stroeer_page_section_v1_section_page_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSectionPageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stroeer_page_section_v1_section_page_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stroeer_page_section_v1_section_page_service_proto_goTypes,
		DependencyIndexes: file_stroeer_page_section_v1_section_page_service_proto_depIdxs,
		EnumInfos:         file_stroeer_page_section_v1_section_page_service_proto_enumTypes,
		MessageInfos:      file_stroeer_page_section_v1_section_page_service_proto_msgTypes,
	}.Build()
	File_stroeer_page_section_v1_section_page_service_proto = out.File
	file_stroeer_page_section_v1_section_page_service_proto_rawDesc = nil
	file_stroeer_page_section_v1_section_page_service_proto_goTypes = nil
	file_stroeer_page_section_v1_section_page_service_proto_depIdxs = nil
}
