// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: stroeer/navigation/v1/navigation_service.proto

package navigation

import (
	v1 "github.com/stroeer/go-tapir/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNavigationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNavigationRequest) Reset() {
	*x = GetNavigationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_navigation_v1_navigation_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNavigationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNavigationRequest) ProtoMessage() {}

func (x *GetNavigationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_navigation_v1_navigation_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNavigationRequest.ProtoReflect.Descriptor instead.
func (*GetNavigationRequest) Descriptor() ([]byte, []int) {
	return file_stroeer_navigation_v1_navigation_service_proto_rawDescGZIP(), []int{0}
}

type GetNavigationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Navigation tree structure including internal and external references
	// The root references has nested references
	// root
	//   - menu
	//   - submenu
	//   - menu
	//   - submenu
	//   - external references
	NavigationMenu *v1.Reference `protobuf:"bytes,1,opt,name=navigation_menu,json=navigationMenu,proto3" json:"navigation_menu,omitempty"`
}

func (x *GetNavigationResponse) Reset() {
	*x = GetNavigationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_navigation_v1_navigation_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNavigationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNavigationResponse) ProtoMessage() {}

func (x *GetNavigationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_navigation_v1_navigation_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNavigationResponse.ProtoReflect.Descriptor instead.
func (*GetNavigationResponse) Descriptor() ([]byte, []int) {
	return file_stroeer_navigation_v1_navigation_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetNavigationResponse) GetNavigationMenu() *v1.Reference {
	if x != nil {
		return x.NavigationMenu
	}
	return nil
}

var File_stroeer_navigation_v1_navigation_service_proto protoreflect.FileDescriptor

var file_stroeer_navigation_v1_navigation_service_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x15, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x76, 0x69,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x6e, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0e, 0x6e, 0x61, 0x76,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6e, 0x75, 0x32, 0x81, 0x01, 0x0a, 0x11,
	0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x6c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2b, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x6e, 0x61, 0x76,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x61,
	0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74,
	0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x61, 0x70, 0x69, 0x72, 0x2f, 0x6e,
	0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x6e, 0x61, 0x76,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stroeer_navigation_v1_navigation_service_proto_rawDescOnce sync.Once
	file_stroeer_navigation_v1_navigation_service_proto_rawDescData = file_stroeer_navigation_v1_navigation_service_proto_rawDesc
)

func file_stroeer_navigation_v1_navigation_service_proto_rawDescGZIP() []byte {
	file_stroeer_navigation_v1_navigation_service_proto_rawDescOnce.Do(func() {
		file_stroeer_navigation_v1_navigation_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_stroeer_navigation_v1_navigation_service_proto_rawDescData)
	})
	return file_stroeer_navigation_v1_navigation_service_proto_rawDescData
}

var file_stroeer_navigation_v1_navigation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stroeer_navigation_v1_navigation_service_proto_goTypes = []interface{}{
	(*GetNavigationRequest)(nil),  // 0: stroeer.navigation.v1.GetNavigationRequest
	(*GetNavigationResponse)(nil), // 1: stroeer.navigation.v1.GetNavigationResponse
	(*v1.Reference)(nil),          // 2: stroeer.core.v1.Reference
}
var file_stroeer_navigation_v1_navigation_service_proto_depIdxs = []int32{
	2, // 0: stroeer.navigation.v1.GetNavigationResponse.navigation_menu:type_name -> stroeer.core.v1.Reference
	0, // 1: stroeer.navigation.v1.NavigationService.GetNavigation:input_type -> stroeer.navigation.v1.GetNavigationRequest
	1, // 2: stroeer.navigation.v1.NavigationService.GetNavigation:output_type -> stroeer.navigation.v1.GetNavigationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stroeer_navigation_v1_navigation_service_proto_init() }
func file_stroeer_navigation_v1_navigation_service_proto_init() {
	if File_stroeer_navigation_v1_navigation_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stroeer_navigation_v1_navigation_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNavigationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stroeer_navigation_v1_navigation_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNavigationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stroeer_navigation_v1_navigation_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stroeer_navigation_v1_navigation_service_proto_goTypes,
		DependencyIndexes: file_stroeer_navigation_v1_navigation_service_proto_depIdxs,
		MessageInfos:      file_stroeer_navigation_v1_navigation_service_proto_msgTypes,
	}.Build()
	File_stroeer_navigation_v1_navigation_service_proto = out.File
	file_stroeer_navigation_v1_navigation_service_proto_rawDesc = nil
	file_stroeer_navigation_v1_navigation_service_proto_goTypes = nil
	file_stroeer_navigation_v1_navigation_service_proto_depIdxs = nil
}
