// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: stroeer/page/article/v1/article_page.proto

package article

import (
	v1 "github.com/stroeer/go-tapir/core/v1"
	v11 "github.com/stroeer/go-tapir/page/stage/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Article page with all render relevant data for the user and SEO bots.
type ArticlePage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The editorial article with the ID of a `GetArticlePageRequest`.
	//
	// Unpublished elements will be filtered according to their metadata.
	Article *v1.Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	// stages for article pages contain companions, links to topic pages, A-Z Modules etc.
	// configuration.fields contains a `stage_type`, which defines the rendering position
	Stages []*v11.Stage `protobuf:"bytes,3,rep,name=stages,proto3" json:"stages,omitempty"`
	// Page navigation including internal and external references
	// The root references has nested references
	// root
	//   - menu
	//   - submenu
	//   - menu
	//   - submenu
	//   - external references
	NavigationMenu *v1.Reference `protobuf:"bytes,4,opt,name=navigation_menu,json=navigationMenu,proto3" json:"navigation_menu,omitempty"`
}

func (x *ArticlePage) Reset() {
	*x = ArticlePage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_page_article_v1_article_page_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticlePage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlePage) ProtoMessage() {}

func (x *ArticlePage) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_page_article_v1_article_page_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlePage.ProtoReflect.Descriptor instead.
func (*ArticlePage) Descriptor() ([]byte, []int) {
	return file_stroeer_page_article_v1_article_page_proto_rawDescGZIP(), []int{0}
}

func (x *ArticlePage) GetArticle() *v1.Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *ArticlePage) GetStages() []*v11.Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *ArticlePage) GetNavigationMenu() *v1.Reference {
	if x != nil {
		return x.NavigationMenu
	}
	return nil
}

var File_stroeer_page_article_v1_article_page_proto protoreflect.FileDescriptor

var file_stroeer_page_article_v1_article_page_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x73, 0x74,
	0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1d, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x21, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x67, 0x65,
	0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x0b, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x50, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x74, 0x72, 0x6f,
	0x65, 0x65, 0x72, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x43, 0x0a, 0x0f, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65,
	0x6e, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65,
	0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x52, 0x0e, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x6e, 0x75, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x61,
	0x70, 0x69, 0x72, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_stroeer_page_article_v1_article_page_proto_rawDescOnce sync.Once
	file_stroeer_page_article_v1_article_page_proto_rawDescData = file_stroeer_page_article_v1_article_page_proto_rawDesc
)

func file_stroeer_page_article_v1_article_page_proto_rawDescGZIP() []byte {
	file_stroeer_page_article_v1_article_page_proto_rawDescOnce.Do(func() {
		file_stroeer_page_article_v1_article_page_proto_rawDescData = protoimpl.X.CompressGZIP(file_stroeer_page_article_v1_article_page_proto_rawDescData)
	})
	return file_stroeer_page_article_v1_article_page_proto_rawDescData
}

var file_stroeer_page_article_v1_article_page_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stroeer_page_article_v1_article_page_proto_goTypes = []interface{}{
	(*ArticlePage)(nil),  // 0: stroeer.page.article.v1.ArticlePage
	(*v1.Article)(nil),   // 1: stroeer.core.v1.Article
	(*v11.Stage)(nil),    // 2: stroeer.page.stage.v1.Stage
	(*v1.Reference)(nil), // 3: stroeer.core.v1.Reference
}
var file_stroeer_page_article_v1_article_page_proto_depIdxs = []int32{
	1, // 0: stroeer.page.article.v1.ArticlePage.article:type_name -> stroeer.core.v1.Article
	2, // 1: stroeer.page.article.v1.ArticlePage.stages:type_name -> stroeer.page.stage.v1.Stage
	3, // 2: stroeer.page.article.v1.ArticlePage.navigation_menu:type_name -> stroeer.core.v1.Reference
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stroeer_page_article_v1_article_page_proto_init() }
func file_stroeer_page_article_v1_article_page_proto_init() {
	if File_stroeer_page_article_v1_article_page_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stroeer_page_article_v1_article_page_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticlePage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stroeer_page_article_v1_article_page_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stroeer_page_article_v1_article_page_proto_goTypes,
		DependencyIndexes: file_stroeer_page_article_v1_article_page_proto_depIdxs,
		MessageInfos:      file_stroeer_page_article_v1_article_page_proto_msgTypes,
	}.Build()
	File_stroeer_page_article_v1_article_page_proto = out.File
	file_stroeer_page_article_v1_article_page_proto_rawDesc = nil
	file_stroeer_page_article_v1_article_page_proto_goTypes = nil
	file_stroeer_page_article_v1_article_page_proto_depIdxs = nil
}
