// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: stroeer/page/article/v1/article_extender_service.proto

package article

import (
	v1 "github.com/stroeer/go-tapir/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// ## `enum QuestionSource`
// Information about the source of the question.
// User questions must be treated differently than questions that we provided.
//
// | Enum value                    | Description                                                  |
// |-------------------------------|--------------------------------------------------------------|
// | `QUESTION_SOURCE_UNSPECIFIED` | unspecified                                                  |
// | `INITIAL_QUESTIONS`           | The question was part of the initial server-side response.   |
// | `USER`                        | The question is an input from the user.                      |
//
// @CodeBlockStart protobuf
type GetAnswerRequest_QuestionSource int32

const (
	GetAnswerRequest_QUESTION_SOURCE_UNSPECIFIED GetAnswerRequest_QuestionSource = 0
	GetAnswerRequest_INITIAL_QUESTIONS           GetAnswerRequest_QuestionSource = 1
	GetAnswerRequest_USER                        GetAnswerRequest_QuestionSource = 2
)

// Enum value maps for GetAnswerRequest_QuestionSource.
var (
	GetAnswerRequest_QuestionSource_name = map[int32]string{
		0: "QUESTION_SOURCE_UNSPECIFIED",
		1: "INITIAL_QUESTIONS",
		2: "USER",
	}
	GetAnswerRequest_QuestionSource_value = map[string]int32{
		"QUESTION_SOURCE_UNSPECIFIED": 0,
		"INITIAL_QUESTIONS":           1,
		"USER":                        2,
	}
)

func (x GetAnswerRequest_QuestionSource) Enum() *GetAnswerRequest_QuestionSource {
	p := new(GetAnswerRequest_QuestionSource)
	*p = x
	return p
}

func (x GetAnswerRequest_QuestionSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetAnswerRequest_QuestionSource) Descriptor() protoreflect.EnumDescriptor {
	return file_stroeer_page_article_v1_article_extender_service_proto_enumTypes[0].Descriptor()
}

func (GetAnswerRequest_QuestionSource) Type() protoreflect.EnumType {
	return &file_stroeer_page_article_v1_article_extender_service_proto_enumTypes[0]
}

func (x GetAnswerRequest_QuestionSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetAnswerRequest_QuestionSource.Descriptor instead.
func (GetAnswerRequest_QuestionSource) EnumDescriptor() ([]byte, []int) {
	return file_stroeer_page_article_v1_article_extender_service_proto_rawDescGZIP(), []int{2, 0}
}

// *
// ## `enum Accept`
// The client can specify the format of the answer text.
//
// | Enum value            | Description                                                  |
// |-----------------------|--------------------------------------------------------------|
// | `ACCEPT_UNSPECIFIED`  | unspecified                                                  |
// | `PLAINTEXT`           | The question was part of the initial server-side response.   |
// | `MARKDOWN`            | The question is an input from the user.                      |
//
// @CodeBlockStart protobuf
type GetAnswerRequest_Accept int32

const (
	GetAnswerRequest_ACCEPT_UNSPECIFIED GetAnswerRequest_Accept = 0
	GetAnswerRequest_PLAINTEXT          GetAnswerRequest_Accept = 1
	GetAnswerRequest_MARKDOWN           GetAnswerRequest_Accept = 2
)

// Enum value maps for GetAnswerRequest_Accept.
var (
	GetAnswerRequest_Accept_name = map[int32]string{
		0: "ACCEPT_UNSPECIFIED",
		1: "PLAINTEXT",
		2: "MARKDOWN",
	}
	GetAnswerRequest_Accept_value = map[string]int32{
		"ACCEPT_UNSPECIFIED": 0,
		"PLAINTEXT":          1,
		"MARKDOWN":           2,
	}
)

func (x GetAnswerRequest_Accept) Enum() *GetAnswerRequest_Accept {
	p := new(GetAnswerRequest_Accept)
	*p = x
	return p
}

func (x GetAnswerRequest_Accept) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetAnswerRequest_Accept) Descriptor() protoreflect.EnumDescriptor {
	return file_stroeer_page_article_v1_article_extender_service_proto_enumTypes[1].Descriptor()
}

func (GetAnswerRequest_Accept) Type() protoreflect.EnumType {
	return &file_stroeer_page_article_v1_article_extender_service_proto_enumTypes[1]
}

func (x GetAnswerRequest_Accept) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetAnswerRequest_Accept.Descriptor instead.
func (GetAnswerRequest_Accept) EnumDescriptor() ([]byte, []int) {
	return file_stroeer_page_article_v1_article_extender_service_proto_rawDescGZIP(), []int{2, 1}
}

// *
// # `⚙︎ GetQuestions`
// ```protobuf
// rpc GetQuestions(GetQuestionsRequest) returns (GetQuestionsResponse) {}
// ```
//
// Returns an array of questions if the given `id` exists, in the vector store,
// an `Error`, otherwise.
//
// | Field name       | Type                | Description                                                           |
// |------------------|---------------------|-----------------------------------------------------------------------|
// | `id`             | `int64`             | [required] Unique id of the article, questions should be returned for.|
//
// @CodeBlockStart protobuf
type GetQuestionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetQuestionsRequest) Reset() {
	*x = GetQuestionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsRequest) ProtoMessage() {}

func (x *GetQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_stroeer_page_article_v1_article_extender_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetQuestionsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetQuestionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []string `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *GetQuestionsResponse) Reset() {
	*x = GetQuestionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsResponse) ProtoMessage() {}

func (x *GetQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_stroeer_page_article_v1_article_extender_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuestionsResponse) GetQuestions() []string {
	if x != nil {
		return x.Questions
	}
	return nil
}

// *
// # `⚙︎ GetAnswer`
// ```protobuf
// rpc GetAnswer(GetAnswerRequest) returns (GetAnswerResponse) {}
// ```
//
// Returns the answer of a question as a string. Otherwise an `Error`.
//
// | Field name       | Type                | Description                                       |
// |------------------|---------------------|---------------------------------------------------|
// | `question`       | `string`            | [required] The question for the returned answers. |
// | `article_id`     | `int64`             | [required] The original article the user read.    |
//
// @CodeBlockStart protobuf
type GetAnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question       string                          `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	ArticleId      int64                           `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	QuestionSource GetAnswerRequest_QuestionSource `protobuf:"varint,3,opt,name=question_source,json=questionSource,proto3,enum=stroeer.page.article.v1.GetAnswerRequest_QuestionSource" json:"question_source,omitempty"`
	Accept         GetAnswerRequest_Accept         `protobuf:"varint,4,opt,name=accept,proto3,enum=stroeer.page.article.v1.GetAnswerRequest_Accept" json:"accept,omitempty"`
}

func (x *GetAnswerRequest) Reset() {
	*x = GetAnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerRequest) ProtoMessage() {}

func (x *GetAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerRequest.ProtoReflect.Descriptor instead.
func (*GetAnswerRequest) Descriptor() ([]byte, []int) {
	return file_stroeer_page_article_v1_article_extender_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAnswerRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GetAnswerRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *GetAnswerRequest) GetQuestionSource() GetAnswerRequest_QuestionSource {
	if x != nil {
		return x.QuestionSource
	}
	return GetAnswerRequest_QUESTION_SOURCE_UNSPECIFIED
}

func (x *GetAnswerRequest) GetAccept() GetAnswerRequest_Accept {
	if x != nil {
		return x.Accept
	}
	return GetAnswerRequest_ACCEPT_UNSPECIFIED
}

type GetAnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	// Deprecated: Marked as deprecated in stroeer/page/article/v1/article_extender_service.proto.
	Sources          []*v1.Article `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	FurtherQuestions []string      `protobuf:"bytes,3,rep,name=further_questions,json=furtherQuestions,proto3" json:"further_questions,omitempty"`
	SourceIds        []int64       `protobuf:"varint,4,rep,packed,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
}

func (x *GetAnswerResponse) Reset() {
	*x = GetAnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerResponse) ProtoMessage() {}

func (x *GetAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerResponse.ProtoReflect.Descriptor instead.
func (*GetAnswerResponse) Descriptor() ([]byte, []int) {
	return file_stroeer_page_article_v1_article_extender_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAnswerResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// Deprecated: Marked as deprecated in stroeer/page/article/v1/article_extender_service.proto.
func (x *GetAnswerResponse) GetSources() []*v1.Article {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *GetAnswerResponse) GetFurtherQuestions() []string {
	if x != nil {
		return x.FurtherQuestions
	}
	return nil
}

func (x *GetAnswerResponse) GetSourceIds() []int64 {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

var File_stroeer_page_article_v1_article_extender_service_proto protoreflect.FileDescriptor

var file_stroeer_page_article_v1_article_extender_service_proto_rawDesc = []byte{
	0x0a, 0x36, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65,
	0x72, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x1a, 0x1d, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x8d, 0x03,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x61, 0x0a,
	0x0f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72,
	0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x0e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x48, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x30, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x22, 0x52, 0x0a, 0x0e, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x1b,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x5f, 0x51, 0x55, 0x45, 0x53, 0x54, 0x49, 0x4f,
	0x4e, 0x53, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x22, 0x3d,
	0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x43, 0x43, 0x45,
	0x50, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x50, 0x4c, 0x41, 0x49, 0x4e, 0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x4d, 0x41, 0x52, 0x4b, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x22, 0xaf, 0x01,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x07, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73,
	0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x42, 0x02, 0x18, 0x01, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x66, 0x75, 0x72, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10,
	0x66, 0x75, 0x72, 0x74, 0x68, 0x65, 0x72, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x73, 0x32,
	0xed, 0x01, 0x0a, 0x16, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2c, 0x2e, 0x73, 0x74, 0x72,
	0x6f, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65,
	0x65, 0x72, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x29, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72,
	0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x61, 0x67, 0x65,
	0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74,
	0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x61, 0x70, 0x69, 0x72, 0x2f, 0x70,
	0x61, 0x67, 0x65, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stroeer_page_article_v1_article_extender_service_proto_rawDescOnce sync.Once
	file_stroeer_page_article_v1_article_extender_service_proto_rawDescData = file_stroeer_page_article_v1_article_extender_service_proto_rawDesc
)

func file_stroeer_page_article_v1_article_extender_service_proto_rawDescGZIP() []byte {
	file_stroeer_page_article_v1_article_extender_service_proto_rawDescOnce.Do(func() {
		file_stroeer_page_article_v1_article_extender_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_stroeer_page_article_v1_article_extender_service_proto_rawDescData)
	})
	return file_stroeer_page_article_v1_article_extender_service_proto_rawDescData
}

var file_stroeer_page_article_v1_article_extender_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stroeer_page_article_v1_article_extender_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stroeer_page_article_v1_article_extender_service_proto_goTypes = []interface{}{
	(GetAnswerRequest_QuestionSource)(0), // 0: stroeer.page.article.v1.GetAnswerRequest.QuestionSource
	(GetAnswerRequest_Accept)(0),         // 1: stroeer.page.article.v1.GetAnswerRequest.Accept
	(*GetQuestionsRequest)(nil),          // 2: stroeer.page.article.v1.GetQuestionsRequest
	(*GetQuestionsResponse)(nil),         // 3: stroeer.page.article.v1.GetQuestionsResponse
	(*GetAnswerRequest)(nil),             // 4: stroeer.page.article.v1.GetAnswerRequest
	(*GetAnswerResponse)(nil),            // 5: stroeer.page.article.v1.GetAnswerResponse
	(*v1.Article)(nil),                   // 6: stroeer.core.v1.Article
}
var file_stroeer_page_article_v1_article_extender_service_proto_depIdxs = []int32{
	0, // 0: stroeer.page.article.v1.GetAnswerRequest.question_source:type_name -> stroeer.page.article.v1.GetAnswerRequest.QuestionSource
	1, // 1: stroeer.page.article.v1.GetAnswerRequest.accept:type_name -> stroeer.page.article.v1.GetAnswerRequest.Accept
	6, // 2: stroeer.page.article.v1.GetAnswerResponse.sources:type_name -> stroeer.core.v1.Article
	2, // 3: stroeer.page.article.v1.ArticleExtenderService.GetQuestions:input_type -> stroeer.page.article.v1.GetQuestionsRequest
	4, // 4: stroeer.page.article.v1.ArticleExtenderService.GetAnswer:input_type -> stroeer.page.article.v1.GetAnswerRequest
	3, // 5: stroeer.page.article.v1.ArticleExtenderService.GetQuestions:output_type -> stroeer.page.article.v1.GetQuestionsResponse
	5, // 6: stroeer.page.article.v1.ArticleExtenderService.GetAnswer:output_type -> stroeer.page.article.v1.GetAnswerResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stroeer_page_article_v1_article_extender_service_proto_init() }
func file_stroeer_page_article_v1_article_extender_service_proto_init() {
	if File_stroeer_page_article_v1_article_extender_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stroeer_page_article_v1_article_extender_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stroeer_page_article_v1_article_extender_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stroeer_page_article_v1_article_extender_service_proto_goTypes,
		DependencyIndexes: file_stroeer_page_article_v1_article_extender_service_proto_depIdxs,
		EnumInfos:         file_stroeer_page_article_v1_article_extender_service_proto_enumTypes,
		MessageInfos:      file_stroeer_page_article_v1_article_extender_service_proto_msgTypes,
	}.Build()
	File_stroeer_page_article_v1_article_extender_service_proto = out.File
	file_stroeer_page_article_v1_article_extender_service_proto_rawDesc = nil
	file_stroeer_page_article_v1_article_extender_service_proto_goTypes = nil
	file_stroeer_page_article_v1_article_extender_service_proto_depIdxs = nil
}
