name: publish

on:
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.client_payload.tag }}
    if: github.event.action == 'publish'

    steps:      
      - run: echo $RELEASE_TAG

      - uses: actions/setup-go@v2

      - uses: actions/checkout@v2
        with:
          path: 'go-tapir'

      - uses: actions/checkout@v2
        with:
          repository: 'stroeer/tapir'
          ref: '${{ env.RELEASE_TAG }}'
          path: 'tapir'

      - name: generate module 
        run: make LANGUAGE=go && make go-mod
        working-directory: tapir
      
      - run: find gen/go
        working-directory: tapir

      - run: find .
        working-directory: go-tapir

      - name: update go-tapir
        working-directory: tapir
        run: |
          rsync -avu --delete gen/go/ ../go-tapir/ \
          --exclude=/.git \
          --exclude=/.github \
          --exclude=README.md \
          --exclude=go.mod
          
      - name: release module
        working-directory: go-tapir
        run: |                    
          git config --global user.name 'go-tapir-bot'
          git config --global user.email 'go-tapir@users.noreply.github.com'
          git remote -vv
          git config --list
          git status
          git add -A
          git commit -vsam "release generated module $RELEASE_TAG"
          git tag -a $RELEASE_TAG -m "$RELEASE_TAG"
          git push $RELEASE_TAG
          git push 

      