name: pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'go-tapir'

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go-tapir/go.mod'

      - uses: actions/checkout@v4
        with:
          repository: 'stroeer/tapir'
          path: 'tapir'

      - uses: bufbuild/buf-setup-action@v1

      - name: generate code
        run: make generate TEMPLATE=buf.gen.go.yaml
        working-directory: tapir
